# Generated by Django 3.1.7 on 2021-03-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
