# Generated by Django 3.1.7 on 2021-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0002_auto_20210316_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ability_cha',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_con',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_dex',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_int',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_mod_cha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_mod_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_mod_dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_mod_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_mod_str',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_mod_wis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_str',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='ability_wis',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='armour_class',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiency',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30),
        ),
    ]
