# Generated by Django 3.1.7 on 2021-03-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0003_auto_20210318_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ability_mod_cha',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ability_mod_con',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ability_mod_dex',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ability_mod_int',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ability_mod_str',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ability_mod_wis',
        ),
    ]
