# Generated by Django 3.1.7 on 2021-03-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0005_auto_20210322_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None-None', max_length=100)),
                ('dice_type', models.IntegerField(default=6)),
                ('dice_qty', models.IntegerField(default=1)),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character_sheet.damagetype')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character_sheet.weapon')),
            ],
        ),
        migrations.DeleteModel(
            name='WeaponDamage',
        ),
    ]
