# Generated by Django 3.1.7 on 2021-03-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0007_remove_damage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damage',
            options={'verbose_name_plural': 'Damage'},
        ),
        migrations.AlterModelOptions(
            name='damagetype',
            options={'verbose_name': 'Damage type'},
        ),
        migrations.AlterModelOptions(
            name='weaponcategory',
            options={'verbose_name': 'Weapon category', 'verbose_name_plural': 'Weapon categories'},
        ),
    ]
