# Generated by Django 3.1.7 on 2021-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0008_auto_20210323_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(to='character_sheet.Weapon'),
        ),
    ]
